baseURL = 'https://pesader.github.io'
languageCode = 'en-us'
title = 'pesader'

theme = "freelancer"
summaryLength=40
paginate=9


[params]
  tagLine = "An enthusiast of technology for good"
  author = "Pedro Sader Azevedo"

  aboutLeft = "I'm a Computer Enginnering student who fully embraces the efficiency of Open Source as well as the right-mindedness of Free Software."
  aboutRight = "Currently, I coordinate my university's Free and Open Source student club, LKCAMP, where I both motivate and teach people to contribute to FOSS."

  homePosts = 3
  homeProjects = 3
  homeBits = 3

  [params.location]
    lineOne = "Campinas - SP"
    lineTwo = "Brazil"

  [params.sbform]
    token = ""

  [[params.social]]
    icon      = "key"
    icon_pack = "fas"
    url       = "https://keyoxide.org/hkp/adcfe1009ec391e7cc38ec13e7497b22c97fe966"

  [[params.social]]
    icon      = "mastodon"
    icon_pack = "fab"
    url       = "https://mastodon.social/@pesader"

  [[params.social]]
    icon      = "linkedin"
    icon_pack = "fab"
    url       = "https://www.linkedin.com/in/pesader"

[related]
  includeNewer = true
  threshold = 80
  toLower = false

  [[related.indices]]
    name = 'tags'
    weight = 100

  [[related.indices]]
    name = 'date'
    weight = 10

[markup]
  [markup.highlight]
    margin = 10
    anchorLineNos = true
    codeFences = true
    guessSyntax = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'friendly'
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputFormats]
     [outputFormats.RSS]
         mediaType = "application/rss+xml"
         baseName = "feed"
